name: pokemon
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/StartScreen.jpg
    - assets/Bulbasaur.png
    - assets/Charmander.png
    - assets/Squirtle.png
    - assets/professorDan.jpg
    - assets/SelectingBackground.png
    - assets/professorOffice.jpg
    - assets/palletTown.jpg
    - assets/playerSprite.jpg
    - assets/RivalSprite.jpg
    - assets/BattleBackGround.png
